BSP-83 Reinstate wildcard import for BND
- In commit 8b051f0 the wildcard import was removed, however the result
  is a number of missing imports. This manifested as a
  NoClassDefFoundError for javax/security/auth/x500/X500Principal
  during testing in Bitbucket Server.